Use new JsonMapper abstraction for serde compatibility
micronaut-projects/micronaut-nats pull request #192
Opened 2021-11-29 09:21 UTC by yawkat

2021-11-29 09:26 UTC, graemerocher requested changes

2021-11-29 09:26 UTC, graemerocher commented on gradle.properties
> +projectVersion=3.2.0-SNAPSHOT
Shouldn't this be 3.1 snapshot?

2021-11-30 08:41 UTC, ilopmar approved these changes

2021-11-30 11:40 UTC, graemerocher approved these changes

2021-11-30 13:27 UTC, merged